### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by fizerkhan** [freeCodeCamp/Mail-for-Good#103]
Great project. Kudos to you guys.

It will be helpful if you add basic steps to run the application and configurations needed for both development and production.

It will be great if you list the stacks used and add some screenshots.

**Comment by AndrewGHC** [comment]
Thanks fizerkhan!

We're going to launch this using docker to ease the process of configuration, so we've held off so far on a setup guide. It's not too hard though, check the .example.env file and set it up. Ensure you have both postgres & redis running, and you'll be able to start the app by running npm run build && npm start - then check localhost:8080.

When this launches we'll have screenshots and far more detail than at present.

Cheers!

**Comment by fizerkhan** [comment]
@AndrewGHC Thanks great mate. I will wait for the launch. :1st_place_medal:
