### ISSUE TITLE
Google auth instructions not sufficiently clear

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/Mail-for-Good#112]
One of our beta testers encountered this screen: 
![](https://www.evernote.com/l/Ar8Ni-ru-ZtEMJoW17b5441nJbazi36SMTkB/image.png)

Do you know what went wrong here? Can we update the documentation to cover this, and ensure that people don't get stuck on this (and in the event that they do, tell them what went wrong?)

**Comment by AndrewGHC** [comment]
Certainly, can you ask them if they set up OAUTH Google credentials?

We can circumvent this by authentication on the server without requiring
this.

Could you also confirm if tonights event is cancelled?

**Comment by QuincyLarson** [comment]
@AndrewGHC I've asked him and I'll let you know what he says.

**Comment by frutsy007** [comment]
Let me just the code pleasec

**Comment by AndrewGHC** [comment]
This is an excellent point and I'll improve the documentation shortly to clarify this process.

**Comment by arcdev1** [comment]
I got this originally as well. Two key steps to resolve:

### Add `http://localhost:8080/auth/google/callback` to the list of authorized callback URIs in Google API.

1. Make sure you've followed the instructions at: [https://support.google.com/googleapi/answer/6158849](https://support.google.com/googleapi/answer/6158849) and updated the .env file with the correct credentials.
2. Login to [Google API Manager](https://console.developers.google.com/apis/)
3. Navigate to `Credentials` in the left-hand menu
4. Select the client ID you created in step 1 above.
5. Under the heading "Authorized JavaScript Origins" include `http://localhost:8080`
6. Under the Heading "Authorized Redirect URIs" include `http://localhost:8080/auth/google/callback

### Enable Google+ API

1. Login to [Google API Manager](https://console.developers.google.com/apis/)
2. Navigate to `Dashboard` in the left-hand menu
3. Click `+ Enable API` near the top right of the window
4. Select `Google+ API` under the heading `Social APIs`

Hope that helps.

**Comment by AndrewGHC** [comment]
Arcdev1 I can't thank you enough for your help on this matter, I shall update the docs shortly. I'd forgotten these steps, having used the same API keys for a number of months. Thanks!

**Comment by karuppiah7890** [comment]
@AndrewGHC The docs are still not updated. But I did know what to change when Google showed an error about unauthorized callback URL.
