### ISSUE TITLE
Detect and warn about SES "sandbox mode" 

### ISSUE THREAD

**Issue by arcdev1** [freeCodeCamp/mail-for-good#113]
When first setting up Amazon SES, the account is in "sandbox" mode. In this mode, no emails will be sent to any address that has not been verified directly by Amazon SES; however, the UI behaves as if nothing is wrong. I still receive a confirmation that the campaign was successful.

I understand why; some send errors are to be expected, so a notification on any single error doesn't make much sense. However, if **zero** emails are successfully sent a warning or notification email would be good.

It would also be super slick if you trapped for messages from the AWS API that match the following (see bottom), and warn the user that their emails may not be reaching their intended target because their SES account may be in "sandbox" mode. It would also be handy to provide some SES guidance in the README or video.

```
message: 'Email address is not verified. The following identities failed the check in region US-EAST-1: <some@email.com>',
code: 'MessageRejected',
statusCode: 400
```

**Comment by AndrewGHC** [comment]
@arcdev1 Thanks again for this - this one has been fixed.
