### ISSUE TITLE
Redis glitch on remote set up (looking for local host)

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/Mail-for-Good#116]

**Comment by arcdev1** [comment]
To add some color to this. I believe using a service like [now](https://zeit.co/now) from zeit.co offers a very compelling use case for this product. One can simply drag and drop the mail-for-good folder or use a single command in the terminal to deploy the app. It's wonderful... in theory.

In practice, you can see my deployment [here](https://zeit.co/billsourour/mail-for-good/zdccuzhsxu) (click on logs and source to see the details). 

The relevant error is:
```
Error: Are you running redis? -  { Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
13:19:57 0|index    |     at Object.exports._errnoException (util.js:1050:11)
13:19:57 0|index    |     at exports._exceptionWithHostPort (util.js:1073:20)
13:19:57 0|index    |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
13:19:57 0|index    |   code: 'ECONNREFUSED',
13:19:57 0|index    |   errno: 'ECONNREFUSED',
13:19:57 0|index    |   syscall: 'connect',
13:19:57 0|index    |   address: '127.0.0.1',
13:19:57 0|index    |   port: 6379 }
```

To be fair, I spent ZERO time debugging this. Chances are it's just a matter of doing a bit of research and modifying the config.

Hope this helps.

**Comment by arcdev1** [comment]
I did some sleuthing today. The answer is simple. `now` does not support compose, nor do they recommend hosting databases. So, looks like it's the wrong place for this software. Feel free to close this issue. 

On a different note. You guys are on Digital Ocean, what size container (droplet) are you using to support this app?

**Comment by CarlJKashnier** [comment]
The smallest droplet is our target.

**Comment by AndrewGHC** [comment]
Thanks for letting us know about that issue, I was going to debug it tomorrow.

We're on the $10 USD box I believe, but this is for 750k+ blasts. The app is designed to be memory efficient, I should try things out with 512mb.

**Comment by arcdev1** [comment]
Just a quick follow-up. I got MFG running on [Amazon EC2 Container Service (ECS)](https://aws.amazon.com/ecs/). I believe this may be a slightly cheaper option than Digital Ocean and it worked like a charm!! 

So, I can now confirm 100% that it was the `now` hosting environment that was the problem. Your codebase and config seem pretty solid.

**Comment by AndrewGHC** [comment]
Great stuff - Now is an interesting tool and not one I'd heard of before, I'll keep it in mind for the future. Cheers!
