### ISSUE TITLE
When creating mailing list allow user to use meaningful name

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/mail-for-good#119]

**Comment by karuppiah7890** [comment]
@CarlJKashnier The application does allow us to give a name to the list to be created right ? Are you talking about editing the name of the list after creating the list ? cc @AndrewGHC

**Comment by AndrewGHC** [comment]
This issue refers to the auto-generated name that encourages laziness on the part of users and may end up in lots of lists/templates/campaigns with confusing names.

@zhakkarn is tackling this.

**Comment by karuppiah7890** [comment]
Oh, okay

**Comment by zhakkarn** [comment]
done with #150
