### ISSUE TITLE
BUG- when using template does not import with plain text selected.

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/mail-for-good#121]

**Comment by karuppiah7890** [comment]
@CarlJKashnier I actually saw a weird behavior. I just realized that there is an exact way to reproduce the bug that I was getting only sometimes.

**Comment by karuppiah7890** [comment]
@CarlJKashnier Please change the issue heading. The error occurs in two cases: 

1. When type of email is chosen as Plain Text and when you use HTML template from the drop down, all the fields are set properly including the type of email field, except the email body.
2. When type of email is chosen as HTML and when you use Plain Text template from the drop down, all the fields are set properly including the type of email field, except the email body.

But no errors occur when the type of email in "Create email" and the template's email type are the same. cc @AndrewGHC

**Comment by AndrewGHC** [comment]
Fixed - thanks @karuppiah7890 (your points here were very helpful while debugging) and @CarlJKashnier.

The app no longer deletes plaintext if html is selected, and vice versa. Instead, it tracks state for both and selectively sends whichever was used to the server. This means it's possible to flip back and forth between plaintext/html without losing your work.
