### ISSUE TITLE
Error while exporting subscribers list as a CSV

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/Mail-for-Good#123]
```
TypeError: Cannot read property 'user' of undefined
app_1       | 07:01:38 0|index    |     at readAccess (/usr/src/app/server/routes/middleware/acl.js:4:21)
app_1       | 07:01:38 0|index    |     at readListAccess (/usr/src/app/server/routes/lists.js:25:44)
app_1       | 07:01:38 0|index    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
app_1       | 07:01:38 0|index    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
app_1       | 07:01:38 0|index    |     at apiIsAuth (/usr/src/app/server/routes/middleware/auth.js:14:14)
app_1       | 07:01:38 0|index    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
app_1       | 07:01:38 0|index    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
app_1       | 07:01:38 0|index    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
app_1       | 07:01:38 0|index    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
app_1       | 07:01:38 0|index    |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
app_1       | 07:01:38 0|index    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
app_1       | 07:01:38 0|index    |     at Immediate.next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
app_1       | 07:01:38 0|index    |     at runCallback (timers.js:674:20)
app_1       | 07:01:38 0|index    |     at tryOnImmediate (timers.js:645:5)
app_1       | 07:01:38 0|index    |     at processImmediate [as _immediateCallback] (timers.js:617:5)

```

**Comment by karuppiah7890** [comment]
The URL which it goes to is : `http://localhost:8080/api/list/subscribers/csv?listId=1&filters={}`

**Comment by karuppiah7890** [comment]
@AndrewGHC I think the change to make is here : https://github.com/freeCodeCamp/Mail-for-Good/blob/master/server/routes/lists.js#L41 ?

From what I see you did in other API endpoints, I think it should be this :

```
app.get('/api/list/subscribers/csv', apiIsAuth, cookieParser, readListAccess, (req, res) => {
    exportListSubscribersCSV(req, res);
});
```

**Comment by AndrewGHC** [comment]
This may well be the case - I will be able to test this tomorrow. In the meantime, if you're able to submit a PR for this that would be brilliant.

Cheers for identifying this issue.

**Comment by karuppiah7890** [comment]
@AndrewGHC Sure. I will send a PR today. And I see you have used `parseJson` middleware even in a GET endpoint like [here](https://github.com/freeCodeCamp/Mail-for-Good/blob/master/server/routes/lists.js#L33), though you have used `req.query` correctly inside the module code. I think `parseJson` should be removed over here as it's unnecessary. And also, I think we should add `parseJson` in [this](https://github.com/freeCodeCamp/Mail-for-Good/blob/master/server/routes/lists.js#L46) POST endpoint which adds subscribers, but this isn't causing any issues currently because I see you haven't added any UI and client side logic to make API calls to this endpoint. But I am curious what's the difference between Subscribers and List Subscribers.

Also, it would be awesome if you can create a small diagram on how the whole application and the logic works. At least the AWS SES, SQS, SNS and the postgres database part. In short, I am talking about creating a diagram for the backend's working. A complete diagram would look cool too. However I don't know much of React to understand the client side

**Comment by karuppiah7890** [comment]
Created a PR for this. Please do review it :)
