### ISSUE TITLE
Put up docs so that developers can help you by contributing!

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/Mail-for-Good#126]
@AndrewGHC @QuincyLarson Please put an instruction guide about how to setup the project locally and run it and test it.

I am having a hard time here, since I don't know much of webpack or anything. Since I am more of a backend fellow

**Comment by AndrewGHC** [comment]
Hi @karuppiah7890, I'm going to update the docs very shortly, thank you for your patience with this and eagerness to try it.
