### ISSUE TITLE
Develop CLI tool if the .env file is misconfigured

### ISSUE THREAD

**Issue by AndrewGHC** [freeCodeCamp/mail-for-good#127]
This could be a simple shell script that lets users configure their environment variables. I'll take a look at this after implementing the work queue.

**Comment by frutsy007** [comment]
Como

**Comment by AndrewGHC** [comment]
https://github.com/freeCodeCamp/mail-for-good/commit/453e774e12a5d85e3933d65b5d925af8481e30c6
