### ISSUE TITLE
Add "Confirm to delete" feature while deleting email templates

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#137]
This would be good feature to prevent any accidental deletes. I didn't think of this while using Mail For Good, but I am trying out MailChimp now and checking out what good features and UI things they have. In future, we could also try out the features provided by other email campaign management tools

**Comment by AndrewGHC** [comment]
This is definitely an enhancement with clear value. I think this one would be great for a first timer or anyone looking to contribute to the project.

**Comment by ZaynMalloc** [comment]
I'd like to work on this.

**Comment by AndrewGHC** [comment]
@ZaynMalloc Please do!

**Comment by karuppiah7890** [comment]
@ZaynMalloc And if you have any issues setting up or anything, just comment here :)

**Comment by AndrewGHC** [comment]
@ZaynMalloc Tomorrow when I have free time I'll write the docs for getting the dev build up, I will ping you once this is up if that sounds good?

**Comment by karuppiah7890** [comment]
@ZaynMalloc May be I can help you with this. Are you on Gitter ? Log into Gitter using your GitHub account and type "karuppiah7890" in search on the sidebar and ping me there :smile:

**Comment by ZaynMalloc** [comment]
Thanks for the help. My gitter is "ZaynMalloc".

**Comment by AndrewGHC** [comment]
@ZaynMalloc Could you confirm the status of this one?

**Comment by ZaynMalloc** [comment]
I just submitted a pull request

**Comment by AndrewGHC** [comment]
@ZaynMalloc Thanks again
