### ISSUE TITLE
Add "Confirm to delete" feature while deleting lists

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#141]
Prevents accidental deletes of lists

**Comment by AndrewGHC** [comment]
@zhakkarn Could you confirm if this one was fixed in the last PR?

**Comment by zhakkarn** [comment]
@AndrewGHC, the last PR only addressed #137

**Comment by ZackWard** [comment]
I would be happy to help with this.

**Comment by karuppiah7890** [comment]
@ZackWard Awesome! Go ahead! You can ask help over here by commenting if you run into something!
