### ISSUE TITLE
Wiki to explain the working of the application in a concise manner, for developers

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/Mail-for-Good#145]
It would be really great to have a wiki to start explaining the working of the application. Starting from the database schema and how things are inserted into and read from it.

And I see some permissions related feature in the application, which I haven't tried properly, but it would be great to know how it all works, so that when new developers come in, they can easily contribute by knowing what's going on and what's the expected outcome of the application and the modules, so that they can fix bugs if they notice any other outcomes

**Comment by AndrewGHC** [comment]
This is a very valid point - I'm currently working on a setup guide for manual installation. Prior to this, I'm going to submit a PR improving the development flow of the app. Leveraging the Wiki for this purpose is certainly something I'll look at.

**Comment by AndrewGHC** [comment]
I'm going to prioritise this as it would make it much easier for people to contribute, I'll have a full manual installation/development guide up within the next few days.

**Comment by karuppiah7890** [comment]
Cool !

**Comment by karuppiah7890** [comment]
Also, we have to make PR against `staging` or `master` ? Because I see two branches. But for now both are at the same point I guess

**Comment by AndrewGHC** [comment]
For the moment - the old staging branch had diverged from master so significantly I replaced it. PRs should point to staging from this point onwards, ideally.

**Comment by karuppiah7890** [comment]
Yes, so that we always keep the master branch stable and not broken. And we can merge `staging` to `master` later after a few PRs, may be during a release.

Also, we need to mention this in the Documentation while talking about Contribution

**Comment by AndrewGHC** [comment]
[Done](https://github.com/freeCodeCamp/Mail-for-Good/wiki/Setup-for-development)
