### ISSUE TITLE
Manage deployment with Now

### ISSUE THREAD

**Issue by AndrewGHC** [freeCodeCamp/mail-for-good#162]

**Comment by hsribei** [comment]
(Assuming this is about Zeit Now.) Is it/will it be possible to deploy to the Now's free tier?

I see that they support Dockerfile deployment, but not sure if Docker compose qualifies, as there are three separate images (sorry if this doesn't make sense, I'm still unfamiliar with docker).

**Comment by hsribei** [comment]
I guess [this is the answer](https://github.com/freeCodeCamp/mail-for-good/issues/116#issuecomment-306658655) I was looking for:

>`now` does not support compose, nor do they recommend hosting databases. So, looks like it's the wrong place for this software.

I'm curious what is the plan towards Now signaled by this issue then. Thanks!

**Comment by AndrewGHC** [comment]
I was looking into ways to simplify deployment of this application. However I don't think that we can simplify the process with Zeit, there's no way of circumventing complexity with it. At some point people do need to get their hands dirty with configuration and setting up a server.

**Comment by karuppiah7890** [comment]
That is quite true. But if we still need to support easy installs, we can look at some docker based servces, which provide environments to install stuff and we can try to bring all the configuration to the web interface instead of hard coding it in `.env`. But this can be put to later versions
