### ISSUE TITLE
check-env-file npm script assumes Python 2 is installed

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#164]
We need to mention that Python 2 must be installed in the setup guide. Also, I had Python 3, so I got an error saying `raw_input` is not defined. I don't know Python, but on searching I found out that the Python 3 equivalent is something different - `input()` and `raw_input()` doesn't work in Python 3.

We must find a solution or work around for this, or I would say - just use NodeJs to do this checking, because Python 2 and Python 3 have so many differences and there's even a command called `2to3` to convert Python 2 source code to Python 3 source code. And people use different versions of Python and some may not use Python at all, so this will be an extra dependency to install.

Also surprisingly, when I got it work with Python 2, the script was asking me to enter values that are already present in the `.env` file. I think the script always asks for all the values ? That's how it looks, I think it has some bugs

The log for my `raw_input` not defined error : 
```
karuppiah@karuppiah ~/F/Mail-for-Good> npm run dev;

> nonprofit-email-service@1.0.0 dev /home/karuppiah/FOSS/Mail-for-Good
> npm run check-env-file && DEV_SEND_RATE=200 NODE_ENV=development node server/index.js


> nonprofit-email-service@1.0.0 check-env-file /home/karuppiah/FOSS/Mail-for-Good
> python ./tools/setup/initial_setup.py


    |==========================================================================================================|
    | This is a short guide for setting up M4G. We'll check a few things to ensure you have things configured. |
    | We will also ask you for key information, and then set things up.                                        |
    |                                                                                                          |
    | If you have already configured your .env file - you've missed one or two settings. We'll add these now.  |
    |==========================================================================================================|
    
 
What is your Google consumer key (client id) and secret key (client secret)?

You can find these here https://console.cloud.google.com/apis/credentials
And read our guide here https://github.com/freeCodeCamp/mail-for-good/wiki/How-to-configure-your-Google-API-Keys
     
Traceback (most recent call last):
  File "./tools/setup/initial_setup.py", line 133, in <module>
    main()
  File "./tools/setup/initial_setup.py", line 38, in main
    GOOGLE_CONSUMER_KEY = raw_input('GOOGLE_CONSUMER_KEY = ')
NameError: name 'raw_input' is not defined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nonprofit-email-service@1.0.0 check-env-file: `python ./tools/setup/initial_setup.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nonprofit-email-service@1.0.0 check-env-file script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/karuppiah/.npm/_logs/2017-07-16T04_10_42_239Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nonprofit-email-service@1.0.0 dev: `npm run check-env-file && DEV_SEND_RATE=200 NODE_ENV=development node server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nonprofit-email-service@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/karuppiah/.npm/_logs/2017-07-16T04_10_42_298Z-debug.log
```

cc @AndrewGHC

**Comment by AndrewGHC** [comment]
Thanks @karuppiah7890.

Python 2 should always be available on any unix-based machine. I will look into replacing raw_input with something cross-compatible with both 2 and 3, it's been a while since I last used python.

I threw it out pretty quickly to ensure users had the right setup installed. I don't want to invest time in making it much more complex, the point is just to create a .env file if one doesn't exist.

**Comment by karuppiah7890** [comment]
@AndrewGHC  Okay.. and I think the script doesn't check the existence of the `.env` file properly. I get asked to type the environment variable values even if my `.env` is always present. I don't why this `if` condition 

```python
if os.path.exists('../../.env'):
    return
```

is not working properly

**Comment by AndrewGHC** [comment]
I've removed the forced python check from the app - I think I was a bit hasty throwing it in there. Can come back to this later.
