### ISSUE TITLE
Maintain a stable version of the app in a separate branch and have stable tag in Docker Hub

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#165]
I keep seeing so many issues in the App's development code and the Docker Hub `latest` and `staging` images. I think we could have a separate branch where we maintain a stable version and test it if it all works fine and push that image with `stable` tag in docker hub

**Comment by AndrewGHC** [comment]
This is definitely required, we shouldn't be using the latest version of Redis and Postgres. I will change this tonight.

**Comment by karuppiah7890** [comment]
:+1:

**Comment by karuppiah7890** [comment]
And we need to test the working of the stable branch in both production (docker images especially) and development environment and keep it clean

**Comment by AndrewGHC** [comment]
I've set this up - but there a few things I need to knock out before release. From now on we'll build the app from this branch. Thanks @karuppiah7890.

https://github.com/freeCodeCamp/mail-for-good/tree/stable
