### ISSUE TITLE
Create a Patreon or Gratipay page for Mail for Good ?

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#171]
We can send all the donations we get to FreeCodeCamp directly

**Comment by karuppiah7890** [comment]
@QuincyLarson and @AndrewGHC  your thoughts ?

**Comment by QuincyLarson** [comment]
@karuppiah7890 We could add a link to the donate page, though I don't think this is super high priority at this point.

**Comment by karuppiah7890** [comment]
Ah, okay. True :+1:
