### ISSUE TITLE
Embeddable email capture form

### ISSUE THREAD

**Issue by hsribei** [freeCodeCamp/mail-for-good#182]
How does a user opt in to a List? Is there an embeddable form or URL I can point them to after deploying? Or is a CSV import the only way at the moment? Thanks!

**Comment by karuppiah7890** [comment]
@hsribei There's an embeddable form. You can find it on the manage lists section, for each list there's an option to check the signup form and the subscribers of the list

**Comment by hsribei** [comment]
@karuppiah7890 I didn't get to this part because I couldn't create a list in the first place. It seems like the only way to create one is to import a CSV file. When going to Create List I only see the field for List name and the Import button. There doesn't seem to be a way to submit the form without importing one. Is this something I'm doing wrong or should I add it as a feature request issue?

I will try with a dummy CSV file. Thanks!

**Comment by karuppiah7890** [comment]
@hsribei Ah, well, you could import a CSV with just one subscriber (may be dummy like you said, or yourself - your email ID) at least, because I doubt if a CSV with just the column headers and no other data will be accepted by the server.

**Comment by hsribei** [comment]
Yes, it worked with the dummy CSV. Just created a file with

```
firstName,lastName,email
First,Last,email@example.com
```
Created an issue #184 for allowing empty lists to be created.

Thanks!
