### ISSUE TITLE
Google Plus Callback Gives Me Internal Server Error

### ISSUE THREAD

**Issue by stanleyyylau** [freeCodeCamp/mail-for-good#188]
So I use follow the README file to set up Mail For Good. I create google + OAuth client ID Credentials and fill it in the .env file. I didn't enter PSQL related credentials. only GOOGLE_CONSUMER_KEY, GOOGLE_CONSUMER_SECRET and GOOGLE_CALLBACK. And I run docker-composer up... the app was successfully accessible via localhost:8080. But when I click login with google +,  it gave me 'Internal Server Error' message. also the console said

`app_1       |   ############################
app_1       |   #   Mail 4 Good started    #
app_1       |   ############################
app_1       |   # Port: 8080
app_1       |   ############################
app_1       |
app_1       | (node:51) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
app_1       | Error
app_1       |     at Strategy.OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:379:17)
app_1       |     at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:166:45
app_1       |     at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
app_1       |     at ClientRequest.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:162:5)
app_1       |     at emitOne (events.js:115:13)
app_1       |     at ClientRequest.emit (events.js:210:7)
app_1       |     at TLSSocket.socketErrorListener (_http_client.js:401:9)
app_1       |     at emitOne (events.js:115:13)
app_1       |     at TLSSocket.emit (events.js:210:7)
app_1       |     at emitErrorNT (internal/streams/destroy.js:64:8)
app_1       |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
app_1       |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)`

Can anyone help with setting up this? I wanted to test, learn and contribute.

**Comment by zhakkarn** [comment]
Hey,
Thank you for reaching out. 
If your end goal is to contribute or examine the code I recommend you follow the [developer setup guide](https://github.com/freeCodeCamp/Mail-for-Good/wiki/Setup-for-development).
Anyway, I'll take some time to look into this issue. So far I managed to reproduce it. I'll keep you up to date.

**Comment by karuppiah7890** [comment]
@stanleyyylau Can you screenshot the webpage ? And also, it's an Internal Server Error from Google ? If yes, then there's usually a link to click to know more details about the error, do click on it and then screenshot it :)

**Comment by stanleyyylau** [comment]
@karuppiah7890  Hi, thanks for your reply. I think this error is caused by the codebase, I didnt see any errors on google api console. page, here's a screenshot

![](https://ws3.sinaimg.cn/large/006tKfTcgy1fiyqjcmsx7j31f20iqacw.jpg)


my .env file is as below

![](https://ws1.sinaimg.cn/large/006tKfTcgy1fiyqk2yv8zj31hy0y2gx6.jpg)

here's the error output by console

![](https://ws3.sinaimg.cn/large/006tKfTcgy1fiyqkpnuuyj31kw0hhqac.jpg)

**Comment by karuppiah7890** [comment]
@stanleyyylau Thanks for the screen shots. :) I will look into too I guess. @zhakkarn Have you found the problem already ?

**Comment by zhakkarn** [comment]
@karuppiah7890 Not yet and unfortunately I won't be able to work on it for the next 4hours.

@stanleyyylau, just a guess, did you try to assign 'http://localhost:8080/auth/google/callback' to the GOOGLE_CALLBACK in your env? 
Also, can I see what you did put in the google console when you retrieved your id and secret (I mostly want to see if the redirections are set properly, just in case)

**Comment by stanleyyylau** [comment]
@zhakkarn Thanks for getting back to me,  I tried it with and without the callback link, neither one is working.

Here is the google console info

![](https://ws3.sinaimg.cn/large/006tKfTcgy1fiyr12p7e6j31kw0tfagd.jpg)

I just start a ubuntu machine with docker, I will try the developer setup guide also to see if this will solve the issue.

**Comment by karuppiah7890** [comment]
@stanleyyylau I am not able to reproduce the error. And I have set the GOOGLE_CALLBACK environment variable in `.env` file

**Comment by AndrewGHC** [comment]
Hi @stanleyyylau,

Can you add:

GOOGLE_CALLBACK=http://localhost:8080/auth/google/callback

To your .env on line 11 in your screenshot and let us know the result?

**Comment by stanleyyylau** [comment]
Hi @AndrewGHC  @karuppiah7890 I try again with the GOOGLE_CALLBACK url on the .env file, but still don't work. but google still returns me error. 

![](https://ws4.sinaimg.cn/large/006tKfTcgy1fiz3wwgm3dj31j80biwju.jpg)

I checked the ./server/secrets.js file, looks like GOOGLE_CALLBACK is automatically set to  http://localhost:8080/auth/google/callback if no value is specified in the .env file

![](https://ws2.sinaimg.cn/large/006tKfTcgy1fiz3v9v3wgj31km0sigsn.jpg)

@karuppiah7890  If our environment is the same, than I guess it's my google + settings. I will double check it and keep you guys updated, thanks so much

**Comment by karuppiah7890** [comment]
If you still have issues, screenshot the Google Error and let us know :)

**Comment by stanleyyylau** [comment]
@karuppiah7890    thanks for your reply, I still can't make it work. the app only gives the msg of ' internal service error'. with no link to google error page. 　I did some googling but still can't figure out if it's possible to check authentication logs directly on google console page.  highly appreciate if you can give me some guidance

**Comment by karuppiah7890** [comment]
@stanleyyylau I don't get you. Are you getting a Google Internal Server Error page ? Or a page like the low ?
![image](https://user-images.githubusercontent.com/12808424/29856367-05d781f6-8d70-11e7-8f65-8af7ee5e6f7a.png)

**Comment by karuppiah7890** [comment]
@stanleyyylau Screenshot what you get currently. And when did you get the Docker Image for the application ? Like, when did you run `docker-compose` command for the first time for Mail for Good?

**Comment by stanleyyylau** [comment]
@karuppiah7890 Thanks for getting back to me , no I still cant get it work even after I reapply for another google API following the README.md file

the error msg I got is below
![](https://user-images.githubusercontent.com/12808424/29856367-05d781f6-8d70-11e7-8f65-8af7ee5e6f7a.png)

Here's what docker console output
![](https://ws4.sinaimg.cn/large/006tNc79gy1fj2mx2cyn8j31kw0uady8.jpg)

![](https://ws4.sinaimg.cn/large/006tNc79gy1fj2myz9sxnj31kw0izwpv.jpg)

I'm not sure if it's google api issue or environment difference issue since I have re create the google api key following the guide. and I search and the internet and cant seem to find a way to check error msg on google console. the only clues I have for debugging is the 'Internal server error' on the /auth/google/back page and the console output by docker

**Comment by karuppiah7890** [comment]
@stanleyyylau You just plan to run Mail for Good right ? I can check what's the issue if you have TeamViewer. My timezone is UTC+05:30, ping me in gitter.im @karuppiah7890

**Comment by stanleyyylau** [comment]
hi @karuppiah7890  thanks for your help. my timezone is https://www.timeanddate.com/worldclock/china/beijing    so there isnt much time difference. I wonder if tonight around 10 is ok for you. thanks in advanced

**Comment by karuppiah7890** [comment]
That's too late. And 10 PM for you or me ? And I think it's better to switch over to gitter.im
And something in the evening (for me) should be good.

**Comment by stanleyyylau** [comment]
@karuppiah7890   I just send you a message on gitter.im,  evening is also ok for me, anytime that's better for u,  I can wait for you, no problem, appreciate your help( by the way I thought we only have like around 30 mins time difference)

**Comment by karuppiah7890** [comment]
No, I think it's 2.5 hrs difference, from what I see in the link you gave me

**Comment by karuppiah7890** [comment]
@AndrewGHC It was a proxy issue. The application wasn't able to connect to Google to do the OAuth stuff (getting tokens etc) but the user was able to see the Google accounts screen as browser had proxy settings and that was shown as passport redirected the user to that page, but after the authorization, when it redirected to `http://localhost:8080/auth/google/callback` , the application was not able to connect to Google to continue and finish the OAuth process.

The issue can be closed.

And @zhakkarn How did you manage to reproduce it ? Or you got some other error ?

**Comment by karuppiah7890** [comment]
@AndrewGHC Next time, we need to make sure that people don't use proxies in their PCs while debugging such issues, and hopefully, no one uses proxies in their servers.

**Comment by zhakkarn** [comment]
@karuppiah7890 I got some other error.

**Comment by AndrewGHC** [comment]
@karuppiah7890 Great investigation there and thanks for the report. So the issue was that the user's browser had a proxy to allow access to Google, but the system itself did not (meaning that the app could not connect to Google)?

Thanks for your help with this.

**Comment by karuppiah7890** [comment]
@AndrewGHC Yes, you are right. :)
