### ISSUE TITLE
Email Announcement URL Error

### ISSUE THREAD

**Issue by bsocial** [freeCodeCamp/mail-for-good#192]
There is a broken link in the email blast that went out announcing Mail For Good. In the email, the link to the AWS deploy how-to points do ../deploy.md which does not exist. It should point to ../aws_deploy.md. Since the email is in the wild perhaps you want to put a copy of ../aws_deploy.md at ../deploy.md?

**Comment by karuppiah7890** [comment]
I think you could have commented on the Medium post and Quincy would have
corrected it :) anyways, someone commented and it's changed now, you can
check the post. Thanks for the heads up though :) You can close the issue

**Comment by karuppiah7890** [comment]
@AndrewGHC This issue can be closed
