### ISSUE TITLE
Use Nginx reverse proxy server for the Application ?

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#193]
This way, people can use SSL certificates in the Nginx config for HTTPS. We could actually provide an automated way to get LetsEncrypt certificates too, as an option.

**Comment by karuppiah7890** [comment]
Okay, looks like you have mentioned it even in the [planned features](https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/planned_features.md)

**Comment by AndrewGHC** [comment]
@karuppiah7890 There's some dev overhead at present required to deploy this app. We've tried to minimise this with EC2 instances with elastic IPs, which use TLS by default. However your point is valid, we can add Nginx to our docker-compose setup & expose the resulting port.

My only concern is that I think we'll inevitably need separate guides for separate services. Adding SSL in a dockerised container to this process will not necessarily make this easier, unless we can use LetsEncrypt with a lib such as Certbot run as a cron job to automate this. All a little speculative at this point.

**Comment by karuppiah7890** [comment]
Yeah, I agree. We need to do quite some automation. Also, actually, there are some more ways to use reverse proxies and get SSL certificates or use own certificates and also prevent from DDoS. For example, people could use a cloud service like cloudflare for this.
