### ISSUE TITLE
Change port number to 80 in local deployment guide

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#194]
https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/local_deploy.md

It's mentioned as 8080 everwhere and asks to use reverse proxy to server on port 80. But it looks like we have recently changed the docker-compose.yml config to map host port 80 to container port 8080

**Comment by AndrewGHC** [comment]
Nice spot, will get round to this next week. If you have the time a PR would be greatly appreciated
