### ISSUE TITLE
Use labels to segregate issues

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#201]
The repository is gaining quite some popularity and many people are 
- Asking questions 
- Suggesting features 
- Reporting bugs
- Reporting Documentation typos and mistakes

I think it would be better to use labels, so we can add some more labels like "feature request" rather than "enhancement" and add "docs" label for sure. And we can actually create an architecture diagram of the whole application and create labels to mention which part(s) the issue is talking about when it comes to a bug. This is how many big projects are segregating their issues and it makes it easy to understand what the issue is just by seeing the label and to also think about whom to talk to regarding the issue. Here's an example from [moby](https://github.com/moby/moby) repo 

![issues](https://user-images.githubusercontent.com/12808424/30523416-865f4a9c-9bfe-11e7-8ea7-ba980da75c71.png)

So, we could even use "area/docs" instead of "docs" and then use "area/docker" for docker related issues and so on. We even need to work on semantic versioning the MfG application so that people can report bugs with version numbers and then we can use version numbers as labels to mention the bug in that particular version !

**Comment by zhakkarn** [comment]
Great input.
Our labels needed a rework for sure. I did not go with your exact solution. The labels on the moby repo are great but they have to manage 2k issues. A simpler system would be easier to manage and use.

**Comment by karuppiah7890** [comment]
@zhakkarn I agree they have lots of issues and have to manage them. But it's still more neat and I am not asking to use many labels, I am just giving ideas on how the label names could look. It's just a matter of preference, like, we could use "docs" or "area/docs" and stuff. And we will get lots of issues too soon. I see M4G trending on GitHub , so many people will try it out

**Comment by zhakkarn** [comment]
@karuppiah7890 Fair point. I did change the labels again to make the categories clearer. I would be keen to use the "area/" prefix but the app is built such a way that you have a frontend,  a backend (with a fairly light codebase) and the docs. Do I miss something or can we just roll with just a "docs" tag?

**Comment by karuppiah7890** [comment]
docs tag should be good!

**Comment by zhakkarn** [comment]
Alright, I'll close this issue until the tags are a problem again or someone come up with another nice idea.

**Comment by karuppiah7890** [comment]
It would also be nice to list out the currently used labels in this thread and the possibility of labels for upcoming issues relating to things instead of just mentioning that "docs" label will be used for docs

**Comment by zhakkarn** [comment]
I might not get what you are saying on this one. If people want a list of the labels they can just go in the "issue" tab and click the "labels" button to see them. As for the second half of the sentence, I will, after doing my best, ask you to rephrase it.

**Comment by karuppiah7890** [comment]
okay
