### ISSUE TITLE
Semantic Versioning of the Application

### ISSUE THREAD

**Issue by karuppiah7890** [freeCodeCamp/mail-for-good#202]
http://semver.org/

I think we need to be strict on doing some semantic versioning so that we know what version is being used by people when they report bugs. This way we know if they are using an old version or not. We need to mention the version in the console logs for people to identify version.

So, we need to make sure we bump the patch number when we fix known bugs. And bump minor version when we add functionality like add new API endpoints. And then bump major version when we change implementation of existing functionality by enhancing it and stuff, like changing an API endpoint's implementation

**Comment by karuppiah7890** [comment]
We also need to release the source code when we bump versions, including patches too

**Comment by AndrewGHC** [comment]
@karuppiah7890 This is something we'll do from this point onwards. In the earlier days, @4iar and I were purely concerned with implementing features and disregarded this but it's something that we'll take heed of from this point forward. Please email me as a follow up to this comment.
