### ISSUE TITLE
Smarthost

### ISSUE THREAD

**Issue by AlroneRhyn** [freeCodeCamp/mail-for-good#205]
Hi Guys !

Mail-for-good seems a pretty nice alternative to mailshimp ! We would like to use it.....with a local exim4 instead of an AWS. Is anybody have already worked on it ?

Thx !!

**Comment by karuppiah7890** [comment]
@AlroneRhyn Thanks for your interest in Mail-for-Good :smile: And about the exim4, we support only AWS SES. We don't support external SMTP servers and I don't think we will support the feature in the future too.  You can check issue #161 to see a small thread about the same. And if you are looking to do email marketing for your business, it makes a lot of sense to use AWS SES. See the thread for more details :smile: 

cc @AndrewGHC

**Comment by karuppiah7890** [comment]
cc @AndrewGHC I think we can close this issue

**Comment by AndrewGHC** [comment]
At present we only SES, though the possibility of third party services remains open. At present though we're rolling with SES as it's the cheapest and for the price, certainly most reliable email service available.

**Comment by manjeshpv** [comment]
open source email server compatible with Amazon SES APIs https://github.com/manjeshpv/emailq works with SMTP
