### ISSUE TITLE
Clickthrough not working

### ISSUE THREAD

**Issue by thegreyham** [freeCodeCamp/mail-for-good#207]
Followed all steps and the email sends to the list. When you click the clickthrough a redirect notice appears.

> The previous page is sending you to an invalid url (http:///clickthrough?url=https://www.freecodecamp.com&trackingId=75124dc9-de4a-4751-8bbf-fa28e5b9865a).

![image](https://user-images.githubusercontent.com/29119439/30699583-04774c82-9edd-11e7-8444-e3180dbac09a.png)

Here is how i have the template setup

 

> Template: 
> GoTo: {freecodecamp/https://www.freecodecamp.com}.
> Email: 
> ![image](https://user-images.githubusercontent.com/29119439/30699664-3e26b468-9edd-11e7-9747-44fb4a2afa3b.png)

When I run docker-compose up I am getting the following, not sure if it could be related:

> app_1       | (node:36) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading

**Comment by karuppiah7890** [comment]
Hi @thegreyham. Thanks for using Mail for Good and reporting this. From the redirect URl, I see that you haven't setup your Domain URL properly. Set it in the settings page and also set it in your .env file in [this line](https://github.com/freeCodeCamp/mail-for-good/blob/master/.env.example#L34)

**Comment by thegreyham** [comment]
Hi @karuppiah7890. Didn't see that, Thanks that worked perfectly.
