### ISSUE TITLE
Dependency on AWS

### ISSUE THREAD

**Issue by alexgleason** [freeCodeCamp/mail-for-good#208]
Hi, I don't know much about AWS; I'm a bit put off by it because it's owned by Amazon wants online services to be managed in an unfamiliar way. I'm comfortable deploying a Linux image and working in a terminal.

Does this software require using AWS? If so, can it be modified to run on a normal Linux server?

I have a mail server that I bootstrapped with [Mail in a Box](https://mailinabox.email/) and I installed Mailman alongside that for email lists. I was hoping to install this on the same server so we can send out campaigns using features that Mailman doesn't have.

Thanks!

**Comment by karuppiah7890** [comment]
@alexgleason Thanks for your interest in Mail for Good App. We currently support only AWS SES for sending mails, and no other external SMTP servers. Check #205 and #161 for more details on this whole thing :smile: 

cc @AndrewGHC I think we can close this issue

**Comment by AndrewGHC** [comment]
@alexgleason We use two key services from Amazon, SES and SNS. The first lets us send emails, and the second lets us know what happened when Amazon tried to deliver them. Beyond this, we do not use any other AWS services.

**Comment by manjeshpv** [comment]
open source email server compatible with Amazon SES APIs https://github.com/manjeshpv/emailq works with SMTP
