### ISSUE TITLE
Is it Serverless?

### ISSUE THREAD

**Issue by deadcoder0904** [freeCodeCamp/mail-for-good#211]
I think if Emails are sent only once a month, then it can be Serverless which might drastically reduce the cost for servers as well.

Idk a lot about AWS or Serverless architecture, but I have a question. 

Is it Serverless or can it be made Serverless ?

**Comment by karuppiah7890** [comment]
@deadcoder0904 Hmm. That's true, using serverless architecture when there's less traffic is good and cost efficient. And currently, it's not serverless. May be we will think about this. But doing the whole thing would require changing lots of stuff in the codebase.

Also, the application is not only for sending mails, it is also used to check the open rates, clickthroughs, bounces. So, it's not like - the user uses the application just once or twice even if they send the mail just once per month, so, they will use it to check how many people are opening the mails and see statistics

**Comment by karuppiah7890** [comment]
cc @AndrewGHC @QuincyLarson

**Comment by deadcoder0904** [comment]
Then maybe u can make sending emails process ServerLess & rest of the process using a Server.

Maybe decoupling things will reduce more cost & 1 million requests are free for Serverless architectures like Google Cloud Functions, Azure Functions & AWS Lambda I guess.

**Comment by deadcoder0904** [comment]
Also another question is rather than sending Emails using AWS SES, can we use something like `nodemailer` on our own server so that it will additionally cut more cost ❔ 

I've also made a helper module which is a Gmail abstraction over `nodemailer` but its not that secure called [email-via-gmail](https://www.npmjs.com/package/email-via-gmail), so can we use this for maybe if someone only has 1000 Email Subscribers, not a million like FCC ❓

**Comment by karuppiah7890** [comment]
@deadcoder0904 Actually, it's quite easy to run a mail server using a lot of self hosted software. But it's not just about sending the Email. It's about sending it to them securely with DKIM signature and stuff and also making sure that it reaches the Inbox / Updates section of the client and not in Spam, also our mail server's IP shouldn't get blacklisted by ISP or other mail servers. This is all taken care by AWS SES and similar Email services like Sendgrid, Mailgun etc

**Comment by karuppiah7890** [comment]
@deadcoder0904 If we are going to run the server in AWS EC2, it's however gonna run 24 x 7 and cost money. Using Serverless partly and Server partly only increases cost if Serverless functions are executed more than the free limit. 

Also, we first have to make the app more stable and achieve some of the goals and fix bugs, and then may be we can discuss about converting the architecture to a serverless architecture and check how complex it will be to decouple things.

**Comment by deadcoder0904** [comment]
Cool. Thanks for the awesome explanation 😄

**Comment by karuppiah7890** [comment]
@deadcoder0904 :+1:

**Comment by deadcoder0904** [comment]
That was a nice explanation. Thanks @AndrewGHC 😄
