### ISSUE TITLE
Missing instructions to workaround broken dashboard on initial setup

### ISSUE THREAD

**Issue by nickangtc** [freeCodeCamp/mail-for-good#212]
Hi all, I'm looking forward to contributing to M4G. I did however struggle for a while to set up the locally hosted project before @zhakkarn eventually pointed out the issue - there's apparently an issue in dev environment. 

I think this info needs to be somewhere until the root cause of the problem is fixed (at this point, I'm unsure what that is).

Specifically, the "broken dashboard" problem is when no user is logged into the dashboard. Upon `npm run dev`, trying to create templates will hang the app (perpetual loading). Login route doesn't work. In Chrome console, there's a bunch of 400s FORBIDDEN requests.

To solve the issue, @zhakkarn told me to:

1. run `npm run build && npm start`
2. click login (which requires Google API keys setup in .env file)
3. shutdown app
4. then finally, run `npm run dev`

This workaround worked for me. In order to make it easier for first-time contributors like me to come on board and start helping, I think this should be added to the Wiki somewhere, perhaps as part of [Setup for development](https://github.com/freeCodeCamp/Mail-for-Good/wiki/Setup-for-development) page.

**Comment by karuppiah7890** [comment]
@nickangtc Thanks for this. And yes, it's true, we need to add it to the Wiki temporarily I think, till the problem is fixed. @zhakkarn Can you help with this Wiki page?

**Comment by nickangtc** [comment]
@karuppiah7890 Ok no problem. 

Do you think it's perhaps a good time to try and resolve this issue? My wild guess here is it's something to do with the authentication with Google+ needed to log into the app.

**Comment by karuppiah7890** [comment]
@nickangtc Yes. @zhakkarn mentioned some infinite looping problems too. PassportJS stuff. Gotta look into it, but idk about react and webpack stuff which serve front end pages

**Comment by vicky002** [comment]
I totally agree.

Please add this in the Wiki installation guide. This worked for me, been struggling a lot since last couple of hours, was not able to figure out the issue. 

@nickangtc Thanks for pointing this out. 👍

**Comment by karuppiah7890** [comment]
I got permissions now. So, I edited the Wiki page. Thanks @nickangtc :smile:

**Comment by hakash** [comment]
Hi all!

I've been trying to get the project up and running locally in a docker environment and I was able to resolve this issue in my installation. 

After dumping the JSON returned from Google in Passport, I saw that I needed to take an additional step in my Google API setup. The Google+ API has to be enabled. You can find the specific page here: https://console.developers.google.com/apis/library/plus.googleapis.com/?q=google%2B

Open that page, and if you have multiple projects, you need to go to the project that you generated the key and secret for oauth in. 

Can you please try it and verify if this solution works? If it does, we need to update docs, not code :)

@karuppiah7890 @zhakkarn @vicky002 @nickangtc

**Comment by zhakkarn** [comment]
👋 @hakash ,
Unfortunately, the problem is different. If you run the app in dev mode you encounter a broken app because you get the react frontend served before authenticating yourself. 

Whereas the expected flow is: 
you query the app 
-> app gives you an HTML document containing a form to authenticate yourself 
-> you authenticate yourself 
-> you get the react frontend served 
-> the react frontend pulls your user data by using the session you just establish before getting the frontend app.

Although, your comment is helpful. It made me look back at the docs in search of your missing step, only to find it in three different places. So yeah, I'll probably need to add "condense and rethink the flow of the doc" in my todos. Sorry for the confusion.

**Comment by hakash** [comment]
@zhakkarn Oh, I got the login page right away, but I guess I ran it as if production then. I'm glad I could be of some help at least, even if it was demonstrating confusion from the docs 😁
