### ISSUE TITLE
Add API access to this service

### ISSUE THREAD

**Issue by joepin** [freeCodeCamp/mail-for-good#214]
In addition to #213, I think the other major feature that email services provide is an API for sending emails/managing contacts. I recognize that this is well beyond the scope of what the project was initially intended to be, but I think that this project would gain tremendously by providing an API for developers to write scripts to automate email campaign creation and sending.

**Comment by karuppiah7890** [comment]
@joepin Yes, we have this in mind :smile: It's already an issue #109 and mentioned in [here](https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/planned_features.md)

**Comment by karuppiah7890** [comment]
So, I think we can close this issue

**Comment by joepin** [comment]
Ah I didn't understand that this is what #109 is referring to! Ok I'm glad to hear!
