### ISSUE TITLE
What is Google API for?

### ISSUE THREAD

**Issue by Rigel772** [freeCodeCamp/mail-for-good#219]
I do not understand how does it relates to Google? Do you need email hosted on Google to use it? Thanks :)

**Comment by wadleo** [comment]
Hi, @Rigel772 the Google API keys setup is for Google authentication in the app. Mail4Good uses Google+ API for authentication.

**Comment by karuppiah7890** [comment]
@wadleo is right. We use Google+ API just for authentication and nothing else, so you don't need to have email hosted on Google to use this application.
