### ISSUE TITLE
Instalation error...

### ISSUE THREAD

**Issue by Rigel772** [freeCodeCamp/mail-for-good#222]
Hello there,
Tried the app and after the command:
**sudo docker-compose up**
I am getting to this point and the prompt freezes:

postgres_1  | LOG:  autovacuum launcher started
app_1       | Clickthrough tracking: Make sure that geoip data has been downloaded: 
app_1       |    $ cd node_modules/geoip-lite
app_1       |    $ npm run-script updatedb
app_1       | 
app_1       |   ############################
app_1       |   #   Mail 4 Good started    #
app_1       |   ############################
app_1       |   # Port: 8080
app_1       |   ############################
app_1       |   
app_1       | (node:46) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
postgres_1  | ERROR:  relation "users" does not exist at character 112
postgres_1  | STATEMENT:  SELECT "id", "googleId", "picture", "token", "email", "name", "sentEmailsCount", "createdAt", "updatedAt" FROM "users" AS "user";

however when I try in browser
**"ec2-IP.eu-west-1.compute.amazonaws.com"**
the dashboard of the app works...

What is the Error about? Will the app work like that?

Thanks a lot :)

**Comment by karuppiah7890** [comment]
The error occurs only for the first time of running the app. It's due to
the non existence of the tables in the database initially, which is later
created by the application. The app will work. If you find any bugs while
using the app in browser, do report it :)

**Comment by Rigel772** [comment]
thank you for fast response :) will report!

**Comment by karuppiah7890** [comment]
@Rigel772 Then I will close the issue for now

**Comment by karuppiah7890** [comment]
cc @AndrewGHC Is there a way to get rid of this error even on the first run of the application ?

**Comment by karuppiah7890** [comment]
cc @zhakkarn
