### ISSUE TITLE
List subscribers error 'Unexpected end of script '

### ISSUE THREAD

**Issue by PtkFerraro** [freeCodeCamp/mail-for-good#225]
In the console log there is nothing about this error...

<img width="1141" alt="screen shot 2017-10-10 at 00 03 26" src="https://user-images.githubusercontent.com/243409/31367597-b1963bec-ad4e-11e7-8ca6-366523db57cb.png">
<img width="1144" alt="screen shot 2017-10-10 at 00 03 14" src="https://user-images.githubusercontent.com/243409/31367601-b64f46ce-ad4e-11e7-8ee2-fab61de21bd4.png">

**Comment by karuppiah7890** [comment]
Thanks for reporting this @PtkFerraro :smile: We will look into it!

**Comment by karuppiah7890** [comment]
And which console log do you mean ? The browser console log or the terminal console log where the Docker containers are running and logging info ?

**Comment by PtkFerraro** [comment]
Hi @karuppiah7890 , 

The terminal console where Docker runs... no error or warning there...

**Comment by karuppiah7890** [comment]
Okay!

**Comment by karuppiah7890** [comment]
How did this error occur ? Did you try to upload the list again and encounter the same error ?

**Comment by PtkFerraro** [comment]
I don´t know why the error message just changed without I change anything. The error now is:

![image](https://user-images.githubusercontent.com/243409/31391207-432992fe-adac-11e7-9c9f-c769bba69af2.png)

You can upload many times the same list and the error is the same.

Bu the emails are uploaded correct, because even with this error, I can click in 'Export Csv' and the file has all emails...

cheers

**Comment by karuppiah7890** [comment]
Oh

**Comment by PtkFerraro** [comment]
Would be something related to permissions? When I click on 'My Permissions' I don´t have any granted.

When I try to grant some permissions to me, pops a message saying 'You cannot offer yourself permissions'

cheers

**Comment by karuppiah7890** [comment]
Okay, we might need some info on this to reproduce the error. Are you the admin of the server ? And are you accessing the system as someone else (with particular permissions) by clicking the settings on the top right and choosing an account ?

**Comment by karuppiah7890** [comment]
Admin as in, do you have access to start and stop the application ?

**Comment by PtkFerraro** [comment]
@karuppiah7890 ,

Yes, I am the Admin and have access to everything. I hosted in Amazon.

I just followed the guid at the Github page. I just did one thing different, changed the docker comopse yam file to get LATEST and not STABLE.

Smoething must be wrong, just sent a campaingn, everything was OK and I´ve got a message saying 'Sent 11 emails', You have left 49.999 emails quota left...
![image](https://user-images.githubusercontent.com/243409/31397164-9f9e4282-adbb-11e7-902a-94703a255478.png)

But I haven´t received any emails and in the dashboard I´ve got a message saying  'You have sent 0 emails'

![image](https://user-images.githubusercontent.com/243409/31397204-c9338602-adbb-11e7-8eb4-831f37394421.png)

**Comment by PtkFerraro** [comment]
@karuppiah7890 , ignore the 0 sent problem, it was because my from address that I was not using the email from the domain that I added to Amazon SES.

The only problem that I have is that I can´t see the email list...

cheers

**Comment by karuppiah7890** [comment]
Oh yes. You need to verify email addresses or domains (whose email ids you will be using to send from) to in SES dashboard, to send the mails. 

And about the bug, yes, we will check it out :smile: I have to check what's the issue. Also, we need to reproduce this to debug it, so, do tell us if you find anything in the browser console, or in the networks tab (with error responses) , and if you did anything different.

**Comment by PtkFerraro** [comment]
@karuppiah7890 ,

Just deleted the other VM and made a new one to make sure that was not a problem of the instalation. Same problem yet (can´t see the subscriber and I don´t have any grant)!

the get of the api works fine and brings the data:
![image](https://user-images.githubusercontent.com/243409/31414998-064d17b6-adf7-11e7-969b-8bc09af995b6.png)

But the error is still the same 'Unexpected end of input'. In the terminal log there is nothing about this error...

About the grant permission problem, still the same too... the terminal log:
![image](https://user-images.githubusercontent.com/243409/31415043-49d238b8-adf7-11e7-8800-dc4226f29696.png)

**Comment by karuppiah7890** [comment]
Some issue on the client side I think. Gotta check.

Also, the permissions, it's for giving permissions to others to look at your data and for managing permissions given by others (to you) to look at their data. And permissions work in the form of offers and accepts concept. You can't really offer a permission to yourself and I think that's what you did and hence the error

**Comment by PtkFerraro** [comment]
Yesterday I made few tests about permissions and I figured that out...

A dummy question, why my installation doesn´t have 'Analytics' on the menu? is there a newer branch of M4G?

cheers

**Comment by karuppiah7890** [comment]
What do you mean by Analytics section ?

**Comment by PtkFerraro** [comment]
My version doesn´t have the analytics menu:
![image](https://user-images.githubusercontent.com/243409/31450311-7e5306c0-ae7f-11e7-9867-9716e5381336.png)

Git image does (https://github.com/freeCodeCamp/mail-for-good):
![image](https://user-images.githubusercontent.com/243409/31450435-c66e442e-ae7f-11e7-80a6-1420d49453d6.png)

**Comment by karuppiah7890** [comment]
I am not sure about this, gotta check with others. But in the current version, it's not present. Currently, all the analytics details (open rates, click throughs etc) come up in the campaigns section in the table

**Comment by 4iar** [comment]
@PtkFerraro - that's totally fine, the recent version does not have a dedicated analytics section. As @karuppiah7890 says, all the analytics stuff is integrated into the campaigns section.

During early development, we intended for analytics to have its own dedicated section, but later decided that it was cleaner to integrate everything into the campaigns section. The screenshot was taken on an older version of the app (before the placeholder analytics section was removed).

**Comment by arunsathiya** [comment]
Following up here to learn what the right CSV import format is. I have tried a bunch of sample CSV files and all such files seem to show errors like "Unexpected end of input" and "Unexpected identifier" when I click on the "Subscribers" button after import.

**Comment by zhakkarn** [comment]
@arunsathiya you need to have one "email" column. The other columns are the variables you'll use in your templates.

**Comment by zhakkarn** [comment]
@arunsathiya Issue #281, destined to first timers is up to make the whole situation a better. If no one bites I'll do it after finishing what's on my plate.
