### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by badruayomaya** [freeCodeCamp/mail-for-good#227]
Hello Team,

Thank you for this great effort. I only just installed mail-for-good and go the errors below after running "sudo docker-compose up":

(node:46) DeprecationWarning: Using the automatically created return                                                                                      value from client.query as an event emitter is deprecated and will be removed in pg                                                                                     @7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
postgres_1  | ERROR:  relation "users" does not exist at character 112
postgres_1  | STATEMENT:  SELECT "id", "googleId", "picture", "token", "email", "na                                                                                     me", "sentEmailsCount", "createdAt", "updatedAt" FROM "users" AS "user";

**Comment by karuppiah7890** [comment]
@badruayomaya Hey, this is just an error that occurs for the first run, but everything should work fine - you can check the browser `http://localhost`

**Comment by jeremycady** [comment]
I cannot make it past this spot on AWS. Freezes up every time.

**Comment by karuppiah7890** [comment]
@jeremycady You mean your VM freezes ?

**Comment by jeremycady** [comment]
@karuppiah7890 Correct. 

Right before:

> postgres_1 | STATEMENT: SELECT "id", "googleId", "picture", "token", "email", "na me", "sentEmailsCount", "createdAt", "updatedAt" FROM "users" AS "user";

mentioned above.

I was required to start/stop my instance several times through the process. I ended up being able to see application and login via Google, but I could not add a user, a list, or add my SES information. It would just sit and think and then ended up crashing again.

Not sure what the issue is. I'll try it on my local machine today and see if I can get working there before attempting on AWS again.

**Comment by karuppiah7890** [comment]
I think it's a resource usage issue. What is your AWS EC2 specs ? And yes,
lemme know how it works in your local machine

**Comment by jeremycady** [comment]
I had setup a t2.micro instance per the instructions.

**Comment by karuppiah7890** [comment]
Okay. I have tried it only on DO servers actually, with 1GB RAM and it worked quite well. I see that t2.micro also has 1GB RAM. Not sure why the issue. Most probably a bug which is leading to too much resource usage. Can you create a separate issue ?

**Comment by karuppiah7890** [comment]
And yes, do try it in a separate t2.micro instance again, after you are done setting up in your local machine. That way you can ensure the issue is reproducible

**Comment by jeremycady** [comment]
I had a huge spike during my first attempt, I think taking up to 75% of CPU. I later removed docker and attempted again, but could have been an issue with it not being a "clean" install.

I believe my initial issue was connecting to the Google API (put in https where it wanted http).

Yep, I'm wanting to do local just so I know have the process down correctly. I'll give it another try on a fresh instance afterward.

**Comment by karuppiah7890** [comment]
75% CPU is too much. And yes, try again later and let me know how it worked

**Comment by zhakkarn** [comment]
After the recent changes, I'll need you to fill up a separate issue if you encounter any problem on deploy/first launch
