### ISSUE TITLE
Need Help In Deploying Mail For Good On my AWS Account

### ISSUE THREAD

**Issue by akbarsheikh** [freeCodeCamp/mail-for-good#230]
Hello,

As i am not very technically sound would love if anyone is willing to help me deploy me this tool on my AWS account? Willing to pay as well.... Donno if this is right to ask here but the process is a bit complicated.

My AWS account is setup, i just need to run it and deply the tool with proer settings

**Comment by karuppiah7890** [comment]
@akbarsheikh You could follow the instructions in this repo or hire a freelancer in various platforms like UpWork, Fiverr etc :smile: Also, do note that the software is still in beta.

**Comment by zhakkarn** [comment]
hi @akbarsheikh , I can spare 2 hours out of this next Tuesday from 1pm to 11pm-ish (minus some inbounds phone calls here and there). Hit me up at valentin.lc.dupas@gmail.com, 1 or 2 hours in advance (the more the better)

**Comment by zhakkarn** [comment]
I forgot to mention it but the above times are UTC/GMT+2
