### ISSUE TITLE
Question: How do you customize the email subscription confirmation page? 

### ISSUE THREAD

**Issue by gilbertginsberg** [freeCodeCamp/mail-for-good#233]
I've set up Mail for Good and I'm using an MFG form on my site http://www.ciudea.co/. If you enter your email in the input field, the form successfully captures the email address and updates the corresponding mailing list I created in Mail for Good. This is all great. 

My question concerns the email subscription confirmation page. If you subscribe, you're brought to a page that looks like this: 

![screen shot 2017-10-30 at 7 21 42 pm](https://user-images.githubusercontent.com/4500679/32200368-adcc79cc-bda7-11e7-92f2-8ca97bde13b1.png)

Any idea on how I'd go about accessing this page so I can customize the html? And so it looks like a more standard confirmation page. For example, something like: 

![screen shot 2017-10-30 at 7 25 45 pm](https://user-images.githubusercontent.com/4500679/32200620-fd283f64-bda8-11e7-82fc-74cc40dcb80d.png)

Would digging around Amazon SES settings be in the right direction?

Thank you.

**Comment by jonathanRinciari** [comment]
It would need to be set up on your backend to handle the submission or use javascript to prevent the redirect that you are currently using and have it handle the request

**Comment by karuppiah7890** [comment]
Hey @gilbertginsberg , @jonathanRinciari is right. Actually, the best thing to do would be to modify the front end and the use the Mail for Good API endpoints and send Ajax requests and redirect to your customised web page for showing confirmation.

**Comment by gilbertginsberg** [comment]
Excellent -- thank you @karuppiah7890 , @jonathanRinciari.
