### ISSUE TITLE
Question: How to include file in email body ?

### ISSUE THREAD

**Issue by hong-duc** [freeCodeCamp/mail-for-good#234]
AWS SES support send email with attachment, but I don't know how to include file in the email body to send.

My question only concerns the server side and the AWS SES api. What should I do ? Thank you.

**Comment by karuppiah7890** [comment]
Currently, the web app doesn't support using attachments in the emails. You need to work on the front end and back end too, to make this change. In front end, you need to provide a way to upload the files, and in back end store attachments and use SES to send the attachments too in the email

**Comment by hong-duc** [comment]
It just that I don't know how exactly to put the attachment to the email body, and from that I will work thing up to the client.

Assuming that I store the uploaded file on the server, what should I do to include it in the email body ?

**Comment by karuppiah7890** [comment]
I don't know. I think @zhakkarn @4iar can tell you about that.
