### ISSUE TITLE
Question: Why templateInstance exists return error ?

### ISSUE THREAD

**Issue by hong-duc** [freeCodeCamp/mail-for-good#235]
https://github.com/freeCodeCamp/mail-for-good/blob/a65eb7a92a288786ef5c78adea5adb380f47a38d/server/controllers/template/create-template.js#L34-L39

It confusing, because when I create new template server always return 400.

**Comment by karuppiah7890** [comment]
Haven't encountered an error while creating a template. I think this should be considered as a issue instead of a question. And what errors did you see at the client side ? Any pop ups saying template already exists ?

**Comment by hong-duc** [comment]
Oh no it not that kind of error, it just an error in console log, because I am change some stuff in the client in the `create template` part and when I test I see that error I thought I do something wrong, so I check and found that part of code on the server and wonder why 😄

**Comment by karuppiah7890** [comment]
Ah, okay. Well, check if there are no errors in the back end by checking
the terminal logs.
