### ISSUE TITLE
mail-for-good @ ubuntu 16.04 -- NOT working

### ISSUE THREAD

**Issue by mstgeo** [freeCodeCamp/mail-for-good#237]
Hi!

I've followed the LOCAL installation procedures for mail-for-good and run the app.

I've set up all things following your manual and got errors while running it as: npm run start

![screenshot-1](https://user-images.githubusercontent.com/33416322/32434208-b22ecdd6-c2dd-11e7-8676-12d5b6111443.jpg)

When I run the app as: npm run dev I have no error but there's no access to the app from the WEB.

8080 port is available from Internet, 

root@mailer:~/Mail-for-Good# nodejs --version
v8.9.0

root@mailer:~/Mail-for-Good# npm --version
5.5.1

Here's the nodejs log file:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle nonprofit-email-service@1.0.0~predev: nonprofit-email-service@1.0.0
6 info lifecycle nonprofit-email-service@1.0.0~dev: nonprofit-email-service@1.0.0
7 verbose lifecycle nonprofit-email-service@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle nonprofit-email-service@1.0.0~dev: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/tmp/mail-for-good/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle nonprofit-email-service@1.0.0~dev: CWD: /root/tmp/mail-for-good
10 silly lifecycle nonprofit-email-service@1.0.0~dev: Args: [ '-c',
10 silly lifecycle   'DEV_SEND_RATE=200 NODE_ENV=development node server/index.js' ]
11 silly lifecycle nonprofit-email-service@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle nonprofit-email-service@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: nonprofit-email-service@1.0.0 dev: `DEV_SEND_RATE=200 NODE_ENV=development node server/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid nonprofit-email-service@1.0.0
15 verbose cwd /root/tmp/mail-for-good
16 verbose Linux 2.6.32-48-pve
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v8.9.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error nonprofit-email-service@1.0.0 dev: `DEV_SEND_RATE=200 NODE_ENV=development node server/index.js`
22 error Exit status 1
23 error Failed at the nonprofit-email-service@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

What can it be ? any thoughts how to solve it ?

regards,
Grzegorz Leśkiewicz

**Comment by karuppiah7890** [comment]
As far as I know, the `start` script is for production, for which you have to run the `build` script first, which created the distribution files in `dist`. So, try running `npm run build` first, before running `npm run start`

**Comment by mstgeo** [comment]
Thx! Working ! :) Enjoy !
