### ISSUE TITLE
Error updating credentials

### ISSUE THREAD

**Issue by jakesorce** [freeCodeCamp/mail-for-good#238]
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been 'POST / host:sns.us-west-2.amazonaws.com x-amz-content-.........................................................................

**Comment by karuppiah7890** [comment]
@jakesorce Hey, I think you need to use the correct AWS Password (in `.env` file) for the user whose Secret key and Access key you are using

**Comment by jakesorce** [comment]
where in .env is AWS password? 

Is it the ENCRYPTION_PASSWORD?

**Comment by karuppiah7890** [comment]
Yes, ENCRYPTION_PASSWORD is the IAM user's password and no it's not the same as the secret key of the user

**Comment by karuppiah7890** [comment]
And it's not the same as your AWS account's password too

**Comment by jakesorce** [comment]
So I've tried everything. I created a new IAM user. I generated a random password for that IAM user. I used that random password as the ENCRYPTION_PASSWORD in the .env file and I'm using the Access Key and Secret Access Key of that same user in the "Settings" of the Mail for Good App. I still get the same error.

**Comment by jakesorce** [comment]
That new user has these permissions set:

<img width="1478" alt="screen shot 2017-11-09 at 12 04 09 pm" src="https://user-images.githubusercontent.com/801470/32624326-23bce004-c546-11e7-8a85-40c0f4c16c40.png">

**Comment by jakesorce** [comment]
Nevermind I figured it out. Had to generate a bunch of credentials and add a bunch of IAM permissions. Maybe the documentation needs to be updated to better reflect this.

**Comment by karuppiah7890** [comment]
There's a video which shows how to add the set of IAM permissions and what permissions (SES, SNS, SQS stuff). And you just need to generate the password for the user randomly afaik. What other difficulty did you face ?
