### ISSUE TITLE
Error Sending Campaign Emails

### ISSUE THREAD

**Issue by jakesorce** [freeCodeCamp/mail-for-good#239]
Hello,

attached you'll find a screenshot of what I'm experiencing.

When I try to send out campaign emails or even just a test email nothing happens.

When I go to settings and add all the correct info for my AWS account it says settings saved successfully, which leads me to believe my account is setup correctly.

My SES account is out of sandbox mode and has a 50,000 daily email limit.

<img width="596" alt="screen shot 2017-11-10 at 2 59 19 pm" src="https://user-images.githubusercontent.com/801470/32680421-d052f358-c627-11e7-9b77-d0b63048fee6.png">

**Comment by jakesorce** [comment]
I had the wrong from email in the campaign. I'll create a new issue for this so either I or someone else can make a pull request to show valid errors if you have the wrong sending email setup in your campaign.

**Comment by karuppiah7890** [comment]
That's true. We need some better error handling and show appropriate errors
to tell the user if he/she is in sandbox mode or if they have used an
unverified email and other possible causes
