### ISSUE TITLE
Unsubscribe Link

### ISSUE THREAD

**Issue by zbhoy** [freeCodeCamp/mail-for-good#240]
Hi,
I am testing out MFG to see if my organization can use it. I have followed the tutorials and got everything approved and am now stuck on my first test email. 

The unsubscribe link did not work. I used the checkbox provided in the software. 

And none of the reports are showing up. It just says 6 emails sent and no further info.

**Comment by karuppiah7890** [comment]
Have you set the domain name in the last field in the settings page along
with the AWS SES settings ?

**Comment by zbhoy** [comment]
How do i do that last field? Sorry i am new with this and only did what the docs said

**Comment by karuppiah7890** [comment]
I am sorry I should have been specific. I am talking about M4G app's
settings page, not AWS. You would have typed your keys in the settings
page, at the end, there will be a field for domain name, fill the app's
domain name (according to your DNS records) over there

**Comment by kumario** [comment]
Hey @karuppiah7890! What if we want to use the M4G unsub process? The unsub URL in the emails appears to be http://unsubscribe/0fbce038-124a-41f5-9c43-6cfec8df01f2 where I imagine it should be http://ec2-34-216-9-4.us-west-2.compute.amazonaws.com/unsubscribe/0fbce038-124a-41f5-9c43-6cfec8df01f2, Would that be an easy fix?
