### ISSUE TITLE
More professional looking success page

### ISSUE THREAD

**Issue by andrewhli** [freeCodeCamp/mail-for-good#249]
Hi there!

Thanks for creating MFG. It's been enjoyable to use!

Currently, after users enter their emails and sign up, they get redirected to a blank page with the following message: {"status":"success","message":"added successfully"}

What's the best way to redirect them to another webpage instead of showing the blank page with that message?

Willing to code this up, so any pointers are appreciated.

Best,

Andrew

**Comment by zhakkarn** [comment]
Hi Andrew,

I glad you appreciate Mail for Good so far.

When you say "another webpage" do you mean a page external to your instance of MfG? Or you do just want to fill the current landing page?

**Comment by andrewhli** [comment]
Either option works:
- Can fill the current landing page with a generic, professional Success page, or
- Can auto-redirect the user to a webpage of our choice
Let me know what's easier.

**Comment by zhakkarn** [comment]
If I'm eyeballing it not too badly, both are very easy to do. I do like the redirect to an external webpage as the goal of the subscription form is to be embedded somewhere by the MfG user so it makes sense to redirect the user somewhere on the app he entered his email instead of a "dead-end" on your MfG instance. Plus it would give the MfG user the choice (but also the responsibility) of his landing page.

My take on this would be to add a hidden input to the subscription form called "redirect_url". You'd fill this as you embed your form wherever you want. This give control to the MfG user over the redirect but if redirect_url is empty we can also adopt the current behavior which is to return some JSON to be used programmatically.

**Comment by andrewhli** [comment]
Ok - Giving it a try and will post a snippet if I can't figure it out. Thanks!

**Comment by andrewhli** [comment]
Here's the new code: 
<input type="hidden" name="redirect_url" value="https://google.com">

What's the best way to call "redirect_url"? I've tried <form action="https://URL/api/list/subscribe" target="_self" method="post">, but MFG returns "Cannot POST /api/list/subscribe"

**Comment by andrewhli** [comment]
Here's the full snippet:
`      <form action="URL/api/list/subscribe" target="_self" method="post">
      <div>
          <div class="subscribe_input">
              <input type="email" value="" name="email" label="signup-email" class="subscribe_input" id="mce-EMAIL" placeholder="Your Email" required>
          </div>
          <div class="subscribe_hidden" aria-hidden="true">
              <input id="redirectbutton" type="hidden" name="subscribeKey" value="5555555" />
              <input type="hidden" name="redirect_url" value="https://google.com">
          </div>
          <div class="subscribe_button">
              <input type="submit" value="Sign Up" name="Subscribe" class="button" id="redirectbutton">
          </div>
      </div>
      </form>`

**Comment by zhakkarn** [comment]
If you put "URL/api/list/subscribe" in the action property of your form you are sending the form data to http://[the url of your instance/localhost]/URL/api/lists/subscribe which is a route that your MfG instance don't know what to do with.

When you talked about willing to code this up I understood that you were ready to work on a pull request to implement a new default landing page or the new redirect behavior we discussed and which doesn't exist. 
My previous comment was an idea of how to handle custom redirection.

Right now you have two options :
-submit a pull request to the Mail-for-Good repo containing changes to add the possibility to use a redirect input
-wait for us to do it. I can lock up two hours tomorrow to do this.

After either of these the pull request will get reviewed and will then be part of the next patch.

Feel free to make me rephrase anything, I'm worried that I'm not able to be clear enough.

**Comment by zhakkarn** [comment]
Mmh, please ignore the first paragraph of the last comment, I understood what you meant afterward. It's 4am here. I'll get back in this issue tomorrow.

**Comment by andrewhli** [comment]
Thanks! I can wait until tomorrow.

**Comment by zhakkarn** [comment]
Alright, a pull request implementing your requested feature has been submitted.

**Comment by andrewhli** [comment]
Really appreciate this! 

Looking forward to cloning from and updating to the latest.

**Comment by andrewhli** [comment]
I was eager to give this a try, so I replaced "ListSignupFormCreator.js" and "subscribe.js" on my server with your changes to those files. Then I ran "sudo docker-compose up".

After following the steps above, should the new redirect feature work, or does the MFG team have to make more changes before the new feature's supported?

**Comment by zhakkarn** [comment]
Here is a confusing thing (we did to avoid some complexity when writing the deploy docs) : when you run "sudo docker-compose up" you are pulling and then using an image of mail-for-good from the docker registry, you are not using the sources you retrieved when you cloned the MfG github repo. So if you want to use this change we have to publish a new updated image of mail-for-good to the docker registry.

**Comment by zhakkarn** [comment]
Anyway, thank you again for having the patience to beta test mail-for-good. With the start of proper versioning and a growing number of our beta users, I'll probably join in on the fun of using a MfG instance for real and use it to post newsletter when we'll release a new version with its patch notes. Do I have your permission to add you to this list? Bear in mind that the first one will take some time to come.

**Comment by andrewhli** [comment]
Yes - I'd be interested in joining the newsletter. 

Sounds like only the MFG team can publish the new Docker image. I can wait for that.

**Comment by andrewhli** [comment]
Hey there. Just wondering if there's a day when we can start using this new feature. Thanks!

**Comment by andrewhli** [comment]
Happy 2018! All the work for this feature seems to be done. Any way to add this feature to production?

**Comment by zhakkarn** [comment]
I had a few things to knock down in order to get everything rolling. My regret is that I kept you in the dark. Expect to see changes at least this week and probably before next Friday.

**Comment by andrewhli** [comment]
Thanks for letting me know. Looking forward

**Comment by zhakkarn** [comment]
Alright, mfg has been updated. To move to update your instance you'll have to kill the process you launched by running ```sudo docker-compose up``` by either running ```docker-compose kill <name of the docker service>``` by default the service calls himself mailforgood_app_1 if you didn't specify a name. Then run ```docker-compose pull``` then ```sudo docker-compose up``` to update your instance and relaunch it

**Comment by zhakkarn** [comment]
I'll let you close the issue if you consider ourselves done with it.

**Comment by andrewhli** [comment]
Appreciate your help with this! I've run the commands you've listed, and MFG has updated. However, after one successful redirect, I'm now running into the following difficulty: 

After submitting the email address, MFG redirects to this page:
![screen shot 2018-01-06 at 7 33 48 pm](https://user-images.githubusercontent.com/5068143/34645638-a0e22300-f318-11e7-8e8a-66782fd98467.png)

Here's the form code I'm using:
<form action="http://mail.test.com/api/list/subscribe" target="_blank">
              <label for="signup-email">Email</label>
              <input type="email" value="" name="email" label="signup-email">
              <input type="hidden" name="subscribeKey" value="3e013136-0542-49ac-9c73-99fe3caca74e" />
              <input type="hidden" name="redirectOnSuccess" value="https://www.google.com" />
              <input type="hidden" name="redirectOnFailure" value="https://www.yahoo.com" />
              <input type="submit" value="Subscribe" name="Subscribe">
</form>

After making the redirect work, I'll go ahead and close this issue. Let me know what can be done here. Thanks!

**Comment by andrewhli** [comment]
Here's how to recreate the issues:

1. If you sign up with a duplicate email address that already exists in the list, then the redirect will work (in my case, it will go to "https://google.com")

2. If you sign up with a new email address that does not exist in the list, then the redirect will go to the mail server (in my case, it will go to "mail.test.com") and return a "Page not found" error. 

How can we successfully redirect when submitting a new email address (as most users will do)?

**Comment by zhakkarn** [comment]
I messed up. You are using it properly.

The docker image has been patched, you'll have to pull it again (sorry) and everything should be fine.
By the way, props to you for posting a good issue description.

**Comment by andrewhli** [comment]
Thanks! The feature works very well. Looking forward to the newsletter you're putting together

**Comment by zhakkarn** [comment]
I won't post a round of newsletter this time as there is only this feature to cover. But stay tuned because a drag and drop interface to generate responsive emails is bound to come.
