### ISSUE TITLE
Internal Server Error Google Auth login

### ISSUE THREAD

**Issue by Yusadolat** [freeCodeCamp/mail-for-good#255]
Hello there, 
I don't know what actually went wrong but i have double check the Docs I followed to recheck, All installation went well except the Google Login. can you please help look to this. Thanks in Advance
![internal](https://user-images.githubusercontent.com/10975011/34297043-fa70b1e8-e715-11e7-946c-a841779d872d.png)

**Comment by zhakkarn** [comment]
Hi, 
Thank you for taking some of your time to test out Mail for Good and to reach out to us.

Did you fill the googleId and secret in the .env?

Could you ssh into your instance (just like you did when deploying) then try to access your instance. Does your terminal display any errors?

**Comment by Yusadolat** [comment]
Thanks for your time @zhakkarn I definitely filled the GoogleID and secret in the env, what actually caused the problem was the **Whitespace** between the Equal sign and the GoogleID. after clearing the whitespace everything works fine. Thanks once again for your time.

**Comment by AlexVipond** [comment]
@zhakkarn I encountered the same Internal Server Error right after choosing which Google account I wanted to use. It happened on both my local installation and my AWS installation. The Google ID and Secret were both filled in without whitespace.

**Comment by zhakkarn** [comment]
@AlexVipond If my memory serves me right, we had a similar case in which the user had a proxy messing with the redirect which following the authentication (the one occurring right after selecting your google account). @karuppiah7890 is the one having most of the details on that one.

**Comment by AlexVipond** [comment]
@zhakkarn thanks, I remember reading through that issue but couldn't figure out if that was my problem. @karuppiah7890 any details are much appreciated!

**Comment by AlexVipond** [comment]
@zhakkarn @karuppiah7890 my local and AWS instances are both working fine now. The only thing I changed was to use a different set of Google API credentials. The credentials were created last night, but the project was created last week. Maybe there's some kind of waiting period before you can connect to the API?

**Comment by zhakkarn** [comment]
Maybe but I remember when I did set up my creds for the first time I was able to run locally MfG the same day. Anyway, good to hear that you have your instances running.
