### ISSUE TITLE
Add HEML

### ISSUE THREAD

**Issue by deadcoder0904** [freeCodeCamp/mail-for-good#259]
It would be nice if it uses https://heml.io/

**Comment by zhakkarn** [comment]
Looks damn nice. I was thinking of using [foundation for emails](https://foundation.zurb.com/emails.html) to up our markup game. I'll look into HEML but our main target are non-profits managed by not-too-tech-savy persons and I'll focus on putting up a drag and drop interface in which you'll be able to drop content into a responsive grid.

**Comment by deadcoder0904** [comment]
Ahh, both are nice. I personally like HEML due to [live preview](https://heml.io/editor). It gives you the direct HTML Code. Idk if Foundation has it. 

Also Drag & Drop will be nice too, but I think it would need a lot of time to implement. This might need a lot of time actually I think to create a full-blown website like Wix or so.

I think until its implemented, HEML integration should be super easy. 

I haven't tried Mail for Good yet, so can't say if it can do it by adding the HTML Code generated by HEML.

**Comment by zhakkarn** [comment]
Foundation is a responsive front-end framework which has a subset dedicated to making responsive emails working with all major email clients. So you can live preview it just like any HTML page you've built up to this point.

I get that HEML would be easier to implement but quite some work has already been put into a drag & drop editor and the effort to finish it would be equivalent to implementing HEML support. I'll just focus on making the deployement easier then I'll probably resume working on the editor.

**Comment by deadcoder0904** [comment]
> Foundation is a responsive front-end framework which has a subset dedicated to making responsive emails working with all major email clients. So you can live preview it just like any HTML page you've built up to this point.

Yep I've used Foundation a year ago & now I recollect it had some Live Preview 😂

> I get that HEML would be easier to implement but quite some work has already been put into a drag & drop editor and the effort to finish it would be equivalent to implementing HEML support.

If its started already, then do it. I thought if its not done, then HEML integration would be easy. Close this if you're going with D&D Editor

**Comment by joepin** [comment]
Just thought I’d throw in my two cents - as an avid Costant Contact user, I would love to see a drag and drop editor. There are several options out there for doing so - take a look at these: 

http://grapesjs.com 
https://github.com/ory/editor

Probably not feasible for v1, but I’m just adding here for potential future versions.

**Comment by zhakkarn** [comment]
thank you @joepin for these suggestions.

I'm already using ory to build the editor. I'll look into grapesJS it looks awesome (but also overkill/out-of-our-league)

**Comment by deadcoder0904** [comment]
For more inspiration, https://designmodo.com/postcards

Only if you haven't build already 🙈

**Comment by deadcoder0904** [comment]
No problem. I'll post more if I find anything. Thanks for making this product better 🙌

**Comment by zhakkarn** [comment]
I'll close this issue and add HEML support in the "dope but not essential" category along with changing quill for grapejs.
