### ISSUE TITLE
Replacing auth through Google+ by regular email/password auth

### ISSUE THREAD

**Issue by zhakkarn** [freeCodeCamp/mail-for-good#266]
I'm proposing to switch to a classical email/password authentication. It would remove work from our users. I see two solutions if we want to move to a one-click installation (and a better adoption rate). We can automate the process of creating credentials then inject them into the .env for every deployment. But I can only imagine doing that using some Puppeteer shenanigans. Or make the solution internal to the app.

**Comment by alexgleason** [comment]
Hi, thanks for developing this! I want to use it, but I don't have a Google account. I refuse to create one because of the privacy implications associated with having one. If there were an option for email/password auth that would be great. :smile:

**Comment by zhakkarn** [comment]
@alexgleason Well, it has been some time but it's done. yay!

**Comment by alexgleason** [comment]
Hooray, thank you! I'm still wanting to use this. :grin:

**Comment by jwulf** [comment]
Can you link to the commit? Or docs?

**Comment by jwulf** [comment]
This doesn't work with the docker image in the `docker-compose` file. You have to rebuild the docker image using the `Dockerfile`
