### ISSUE TITLE
{appURL}/login should redirect to {appURL}/ when a user is already authenticated

### ISSUE THREAD

**Issue by zhakkarn** [freeCodeCamp/mail-for-good#270]

**Comment by rkpattnaik780** [comment]
I am interested to work on this issue.

**Comment by DarkMethod** [comment]
Where is it redirecting to if not {appURL}?

**Comment by zhakkarn** [comment]
This is not the issue. The issue is, once you are logged-in, you can query {appURL}/login which is http://localhost/login in your case and be presented with the login form. What is needed is to redirect the logged-in user to http://localhost/ if he queries http://localhost/login

**Comment by zhakkarn** [comment]
^made the title clearer (...I hope)

**Comment by HassanAli321** [comment]
#273

**Comment by palpalikta** [comment]
i would like to work on the issue

**Comment by DilanLivera** [comment]
Hi @zhakkarn, is this issue fixed? Could I work on it? Thanks.

**Comment by stefanosu** [comment]
Could I work or help with this issue?

**Comment by gideonnnalue** [comment]
i would love to work on this issue

**Comment by Asjas** [comment]
@gideonnnalue This is already fixed in #339.

I just need to test if it works and then I'll merge it.

**Comment by yonis9** [comment]
Hi, can I work on this issue?

**Comment by Asjas** [comment]
Hi @yonis9, This issue was fixed in #339. I just had to merge the PR.
