### ISSUE TITLE
HTML Email delivered in plain test

### ISSUE THREAD

**Issue by motdde** [freeCodeCamp/mail-for-good#271]
When sending HTML emails, I get the code in plain text. I don't know if this is an issue or I just don't know how to use the app.

I also get payload error sometimes when adding template

Someone help, please

**Comment by zhakkarn** [comment]
Tried on my end. I can't reproduce your problem. Could you provide me with a description of how you managed to encounter this problem? 

I am assuming that you know the [limitations of HTML emails](https://kb.mailchimp.com/campaigns/design/limitations-of-html-email)

**Comment by motdde** [comment]
I use emailframe.work as a boilerplate which I think has handled the limitations.

**Comment by zhakkarn** [comment]
Alright, I failed to understand what you were doing. One of the main missing pieces right now is the ability to import/paste your own HTML into the editor. Right now we have "HTML templates" as in "use the WYSIWIG editor" but not as "give us raw HTML"

**Comment by motdde** [comment]
Okay, I had to use mailblast.io eventually.

**Comment by zhakkarn** [comment]
Cool, I'm glad that you found something that fits you. Moonmail.io is quite nice too, you might want to take a look at it before committing to mailblast.io
