### ISSUE TITLE
Following aws_deploy commands and have an error

### ISSUE THREAD

**Issue by harrydry2** [freeCodeCamp/mail-for-good#275]
I've just read the command: 

`ssh -i "<path to the key file you downloaded earlier>" ubuntu@<your Public DNS (IPv4) from Amazon>` 

And I've got the following error: The authenticity of host 'ec2-18-232-190-231.compute-1.amazonaws.com (18.232.190.231)' can't be established. Permission denied (Public Key)

Would really appreciate  some help. Got 10k emails needing sending!

**Comment by zhakkarn** [comment]
Just to be sure. In a terminal, you did input something like this : 
```  ssh -i "200118Main.pem" ubuntu@ec2-18-232-190-231.us-west-2.compute.amazonaws.com```

If the .pem file is sitting in you /home you can copy paste as is the command given to you when you click actions>connect from the page looking like [this image](https://i.imgur.com/wgO5xHA.png)

**Comment by zhakkarn** [comment]
@harrydry2 I know it has been a long time since you submitted your issue but now Mail for Good has changed its deployment method and is now as easy as clicking a few buttons.

I'm gonna close this issue as it can't happen again.
