### ISSUE TITLE
I can't import lists

### ISSUE THREAD

**Issue by Dejesumensaje** [freeCodeCamp/mail-for-good#276]
I have a problem. When I try to upload a csv, I got a confirmation message but the list stays empty. Also, I'm trying to send a test mail but it loops forever.

**Comment by zhakkarn** [comment]
Did you set up your SES account on the setting page (at the bottom of the menu on the left)? Can we have a sample of your CSV?

**Comment by zhakkarn** [comment]
Can you take a look at the last row?

**Comment by Dejesumensaje** [comment]
It worked! Ty so much.
