### ISSUE TITLE
ERROR:  relation "settings" does not exist at character 204

### ISSUE THREAD

**Issue by rifkegribenes** [freeCodeCamp/mail-for-good#278]
Hi, last week I was able to deploy successfully on AWS and send emails, but now that I'm trying to run it locally I can't get it set up.

I followed the instructions here: https://github.com/freeCodeCamp/mail-for-good/blob/master/docs/local_deploy.md

and after running `sudo docker-compose up` i got the following error:

```
postgres_1  | ERROR:  relation "settings" does not exist at character 204
postgres_1  | STATEMENT:  SELECT "id", "amazonSimpleEmailServiceAccessKey", "amazonSimpleEmailServiceSecretKeyEncrypted", "amazonSimpleQueueServiceUrl", "region", "whiteLabelUrl", "email", "createdAt", "updatedAt", "userId" FROM "settings" AS "setting";
```

i see there is a previous issue that references this same error (#172 ) and the advice was to change line 6 in `docker-compose.yml` — change tag to `latest`. i have tried this too but am still getting the same error.

any other ideas how to resolve this?

thanks!

**Comment by zhakkarn** [comment]
On the first launch, you may see this error or the one below
```
postgres_1  | ERROR:  relation "users" does not exist at character 112
postgres_1  | STATEMENT:  SELECT "id", "googleId", "picture", "token", "email", "name", "sentEmailsCount", "createdAt", "updatedAt" FROM "users" AS "user";
```
This is because you have launched a fresh MfG and there is no user nor user AWS configuration (aka "settings") yet. These errors won't be displayed once you have logged into your instance and filled up the setting page.

Did you try to visit localhost regardless?

**Comment by rifkegribenes** [comment]
@zhakkarn this is a different error though, it's not the `"users" does not exist` error, mine says `relation "settings" does not exist`. i'm getting the "users" error as well but was not worried about it because i saw from other issues that this is normal on first login. i'm going to try reinstalling everything and starting over and see if i can get it to work... it's working fine on AWS

**Comment by zhakkarn** [comment]
@rifkegribenes What I failed to convey is that it is a different error but the same cause. Before replying I relaunched the app through docker-compose after clearing all anonymous volumes and recreating the containers. I got both errors then visited http://localhost/ and got the app served.

**Comment by rifkegribenes** [comment]
@zhakkarn thank you, i just switched back to `stable` in `docker.compose` and rebuilt and now it is working! thank you for your response, i'll close issue.
