### ISSUE TITLE
Difference between Sendy & Mail For Good?

### ISSUE THREAD

**Issue by deadcoder0904** [freeCodeCamp/mail-for-good#279]
Recently I got to know about [Sendy](https://sendy.co) & both the services look similar to me.

The pricing is also similar ,i.e, $ 1 = 10000 emails & both are Self Hosted Services. 

One difference I found is it has a one-time fee of $59 & for every major release updates won't be free.

Anyone with knowledge of Mail Server care to explain the difference between both❓

**Comment by NoelLH** [comment]
I had a quick look at it while researching options that included Mail for Good. As you say, the one time fee is a difference, and more importantly the fact the code is not open source. This pretty fundamentally changes how the commitment to a given tool works.

I think the current position of features developed is not hugely different, but the impression I got is that Sendy has been there for a while but is not being super-actively developed right now - this is just guesswork from their site and versions of stuff I inferred they're probably using.

All quite subjective, but Mail for Good seems to me like it's less mature but has the potential to move way ahead on features eventually, depending on the level of interest from orgs and resulting momentum.
