### ISSUE TITLE
Make the "email" columns of the CSV import insensitive to case and special characters

### ISSUE THREAD

**Issue by zhakkarn** [freeCodeCamp/mail-for-good#281]
While importing a list of subscribers the app should translate the different ways of writing "email" to exactly "email".

e.g:
"Email"->"email"
"EMAIL"->"email"
"e-mail"->"email"

**Comment by Gabbyjose** [comment]
hey there, is this ticket still available? i'm happy to help!

**Comment by zhakkarn** [comment]
Hi @Gabbyjose , 
As of yet I no one has been assigned to resolving this issue and no pull request has been submitted.

**Comment by Gabbyjose** [comment]
Hi @zhakkarn, could you show me where in the code this fix needs to happen? I can take a look at it this weekend!

**Comment by zhakkarn** [comment]
I'm split on this. Finding where is the problem lies represent 80-90% of the work on this one and "First timers only" issues are made to let newcomers onboard themselves more easily by giving them something to look for while they are looking around for the first time.
What I suggest is that you run mail for good on your machine, play with the app and look at the structure of the /client folder. You will most likely see which component maps to which screen/view. 

The current problem we have to solve here is that if you import a list of subscribers from a .csv you have to provide a .csv with a column titled exactly "email" but we need to make the solution a little more robust by letting the user upload .csv with columns such as "Email", "e-mail" or any sensible variation (at least we need to make case insensitive)

**Comment by Gabbyjose** [comment]
I see what you're saying, I'll go ahead and clone the code and begin playing around with it. I'm working on a Mac and need to set up some of the pre-reqs you have on your wiki, so I can start there. Once I dive into the code I can let you know if I have any questions!

**Comment by dynelight** [comment]
I'd love to work on this if it is still available.

**Comment by zhakkarn** [comment]
looks like it is.

2018-05-28 21:39 GMT+02:00 Esteban Rodriguez <notifications@github.com>:

**Comment by 9jaswag** [comment]
seems like lots of folks have indicated interest in this, is it still available? @zhakkarn

**Comment by zhakkarn** [comment]
There's already a PR covering this. I just forgot to close the issue. Sorry.
