### ISSUE TITLE
Unable to save credentials

### ISSUE THREAD

**Issue by wimo7083** [freeCodeCamp/mail-for-good#289]
Hi there, I tried the heroku click to deploy to test this out and I'm running into issues. The deployment works fine and I'm able to login using the default credentials, and login using those. But when I go to add the AWS SES credentials I get a spinner icon that keeps going. Eventually the spinner icon stops and there's an icon saying "not saved" over each one.

**Comment by zhakkarn** [comment]
Alright, thanks for reporting this. I will get on it tomorrow. I'll keep you posted.

**Comment by wimo7083** [comment]
Thank you for the assistance. I'm not sure what's causing it and if you need more details or specifics I can assist with that.

**Comment by zhakkarn** [comment]
Alright, thank you for reporting this. It is now fixed. I'll close this issue and will reopen it in case you keep encountering this problem.
I'll need you to delete your instance on heroku and deploy a new one as it is (for now) the easiest (and kind of embarrassing to tell) way to update. I'll get around a better Updating flow after putting a continuous integration pipeline.
