### ISSUE TITLE
Difference between Local & Server Deployment?

### ISSUE THREAD

**Issue by deadcoder0904** [freeCodeCamp/mail-for-good#299]
How fast Mail For Good is Locally & on Server so I can choose if I can go with Local Deployment without the need of Redis & PostgreSQL on server.

From what I can understand, if I go full server, then I have to use AWS SES & then Redis & PostgreSQL on the server as well.

And if I go Local, I only have to use AWS SES on Server rest I can do locally right?

And if I go Local, how long will it take to send let's say 5000 emails? Will it heat up my PC? Probably dumb questions but gotta ask someday 😂

**Comment by zhakkarn** [comment]
running on a server or your desktop as the same outcome if you have the same computing power on both sides. It probably won't heat up your machine (I wouldn't try it on a desktop at first because I don't encourage running any heavy stuff on a laptop).
You can have a postgres and a redis hosted separately if you want you'll just have to specify them in the .env file and start the server with ```npm start```.
I don't know how long it will take on your machine but take a look at your SES account. Your send rate is capped and it is probably going to be the bottleneck in your case, not your processing power.

**Comment by zhakkarn** [comment]
Honestly it depends mostly on the maximum send rate of your SES account.

**Comment by zhakkarn** [comment]
let's say you have the same basic send rate as I do. 14 emails/second, you'd have to no turn off your desktop for ~20 hours straight. So yeah it doesn't seem like a good option.

You can run almost everything at once if you take the Dockerfile, docker-compose.yml and your .env file on a server and run ```docker-compose up```. When I say 'almost' I mean that you'll still have to setup your SES account but that should be it.

**Comment by deadcoder0904** [comment]
@zhakkarn But that's for a lot of emails right, to be exact, 10,08,000, i.e, 1 million 8 thousand subscribers right?

Another question is, as it is using AWS SES so I just need to submit CSV file & Template & rest is handled by SES. So why my `localhost:8000` server needs to be ON once its sent the data to SES?

**Comment by zhakkarn** [comment]
@deadcoder0904 gadamn, I slipped on my calculator like a dumbass. Indeed, It would take 6min to send your 5000 emails.  So you don't really need a server, your personnal computer will be just fine.

The app is continuously sending receiving from and sending data to SES. This is why it needs to stay ON during the whole blast.

**Comment by deadcoder0904** [comment]
Appreciate it. Thank you so much. Also, as I am not gonna send more than 5 emails per month, how cheap can a server be for this stuff? Can it be free?

**Comment by zhakkarn** [comment]
For any super short sendings, you can definitely use a free Heroku instance, just use the button on the Readme of this repo. You may want to check [the limitations of the free Heroku instances](https://www.heroku.com/free) the only problematic one imo is that your app can't be up more than 18h per day so you may have someone filling the subscribing form for one of your lists and send it during the forced rest time of your app. Nullifying the subscription.

**Comment by deadcoder0904** [comment]
@zhakkarn Hey can you recommend on AWS if you have any experience with it?

Do you think AWS On Demand is okay for it?

Also, there are lots of solutions on AWS EC2 - On-Demand, Reserved Instances, Spot Instances, Dedicated Hosts & Per-Second Billing. Can you tell me which one would be inexpensive & effective?

**Comment by zhakkarn** [comment]
I don't have enough experience with Amazon EC2 to recommend anything. If I were to use Amazon to host the app I'd first research how I could use Lightsail to run the app on a single t2.micro instance. But outside of that, I can't really orient you.

**Comment by deadcoder0904** [comment]
Thanks again for all the help. I am reading lots of docs but its overwhelming so I might go with Heroku instead. Lets see :)
