### ISSUE TITLE
Heroku launch does not work

### ISSUE THREAD

**Issue by mostafachatillon** [freeCodeCamp/mail-for-good#330]
here is the screnshot when I try with heroku ![heroku](https://user-images.githubusercontent.com/8183572/59556731-e5500000-8fc7-11e9-97e1-2a179109b3af.png)

**Comment by JoshEvanJohnson** [comment]
This is fixed by @lordofthelake in PR #327. The JSON of app.json is not valid. This PR corrects it. Validated my own fork to get it deployed for me in heroku and to start the PR process and looked through open PRs before submitting to find it at the top.

**Comment by Asjas** [comment]
Fixed in #327. Closing
