### ISSUE TITLE
How to install in host like Hostgator ... is their a video explain this?

### ISSUE THREAD

**Issue by ahmedadelnew** [freeCodeCamp/mail-for-good#332]
How to install in host like Hostgator ... is their a video explain this?

**Comment by Asjas** [comment]
There isn't a video that explains how to install `mail-for-good` on Hostgator. I took a quick look at the [Web Hosting](https://www.hostgator.com/web-hosting) of Hostgator and it seems to support `wordpress`, `joomla`, `drupal`, etc. but not Node.js apps.

You would have to use either their [Linux VPS Hosting](https://www.hostgator.com/vps-hosting) or [Dedicated Servers](https://www.hostgator.com/dedicated-server). You would then install Node.js, Nginx or Apache and configure everything.
