### ISSUE TITLE
CONTRIBUTING link is broken

### ISSUE THREAD

**Issue by AblingerOscar** [freeCodeCamp/mail-for-good#335]
The link given in the [CONTRIBUTING file of this repository](https://github.com/freeCodeCamp/mail-for-good/blob/master/CONTRIBUTING.md) to FreeCodeCamp's contribution guideline seems to be broken.
Expected link (probably): https://github.com/freeCodeCamp/freeCodeCamp/blob/master/CONTRIBUTING.md
Given link: https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/CONTRIBUTING.md

**Comment by Asjas** [comment]
Fixed in #336
