### ISSUE TITLE
Using f-string in print function.

### ISSUE THREAD

**Issue by razinc** [freeCodeCamp/mail-for-good#344]
Hi, not an issue but I would like to replace the current print statement with f-string, if it's okay.

**Comment by Asjas** [comment]
Hi, @razinc.

The current iteration of the project isn't being maintained. We will only fix security issues on this version but we are not going to make any other changes.

Please see issue #329 where we will take feature requests for the new version of Mail for Good that we are going to start on.

**Comment by razinc** [comment]
Thanks for the reply @Asjas.
