### ISSUE TITLE
Your entire project is morally represensible

### ISSUE THREAD

**Issue by ddevault** [freeCodeCamp/mail-for-good#357]
Your entire project is morally represensible, and you should delete it immediately and reflect on your actions and the evil you have wrought upon humanity. *You are a bad person*.

It's really fucking simple: spam is evil, and you are conducting evil business. How you call yourself "mail for good", let alone how you sleep at night, is beyond me.

**Comment by QuincyLarson** [comment]
@ddevault We make it easier and less expensive for nonprofits to send emails to their mailing lists. If that's your opinion of the project, you are entitled to it.

**Comment by ddevault** [comment]
What you do is enable spam. You are a spammer. The word "spammer" is synymouos with "bad person" and you know it, you just cognative dissonanced your way into being able to sleep at night because being a bad person is probably how you make a living.
