### ISSUE TITLE
Implement fixes/changes 23/02/17

### ISSUE THREAD

**Issue by 4iar** [freeCodeCamp/Mail-for-Good#95]
- [x] Prevent extra line breaks from being added.
- [x] Fix issue with test emails: sending a test email results in an err (400 response) and breaks campaign sending (requiring a page refresh before a campaign can be sent).
- [x] Notification updates are no longer received after the page is refreshed. For example, after uploading a csv and the page is refreshed there will be no progress update notification (e.g. x rows processed) and no import success notification (even though everything is fine server-side).
- [x] Keep frontend responsive during csv imports. At the moment it is difficult to create a template while importing a csv because it takes so long to load the templates page.

**Comment by AndrewGHC** [comment]
Linebreak issue ref https://github.com/quilljs/quill/issues/1341
